/*<script>*/
var _fgq = [];
function loadGameApi(d, url, fgJS, firstJS) {
    fgJS = d.createElement('script');
    firstJS = d.getElementsByTagName('script')[0];
    fgJS.src = url;
    fgJS.onload = function() {
        if (typeof fg_api == "function" && typeof famobi != "undefined" && famobi instanceof fg_api) {
            return;
        }
        famobi = new fg_api({
            "features": {
                "highscores": 0,
                "menu": 0,
                "fullscreen": 1,
                "screenshot": 0,
                "payment": 0,
                "ads": 0
            },
            "game_i18n": {
                "default": {
                    "Loading...": " ",
                    "page1.page.title": "1\/4",
                    "page2.page.title": "2\/4",
                    "page3.page.title": "3\/4",
                    "page4.page.title": "4\/4",
                    "bear.label": "Gấu",
                    "cow.label": "Bò",
                    "crog.label": "Cá sấu",
                    "dolphin.label": "Cá heo",
                    "fish.label": "Cá chép",
                    "hamster.label": "Chuột",
                    "lion.label": "Sư tử",
                    "lioness.label": "Hổ",
                    "penguin.label": "Chim cánh cụt",
                    "rino.label": "Tê giác",
                    "rooster.label": "Gà trống",
                    "seal.label": "Hải cấu",
                    "snake.label": "Rắn",
                    "star.label": "Sao biển",
                    "whale.label": "Cá voi",
                    "wolf.label": "Chó sói",
                    "bear.description": " ",
                    "cow.description": " ",
                    "crog.description": " ",
                    "dolphin.description": " ",
                    "fish.description": " ",
                    "hamster.description": " ",
                    "lion.description": " ",
                    "lioness.description": " ",
                    "penguin.description": " ",
                    "rino.description": " ",
                    "rooster.description": " ",
                    "seal.description": " ",
                    "snake.description": " ",
                    "star.description": " ",
                    "whale.description": " ",
                    "wolf.description": " ",
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next",
                    "more_games_image_prefix": "",
                    "more_games_image": "images\/logo.png",
                    "more_games_url": "http:\/\/game24h.vn",
                    "preload_image": "\/html5games\/gameapi\/v1\/invisPreloadImage.png",
                    "test_preload_image": "\/html5games\/gameapi\/v1\/testPreloadImage.png"
                },
                "de": {
                    "bear.label": "B\u00e4r",
                    "cow.label": "Kuh",
                    "crog.label": "Krokodil",
                    "dolphin.label": "Delfin",
                    "fish.label": "Fisch",
                    "hamster.label": "Hamster",
                    "lion.label": "L\u00f6we",
                    "lioness.label": "Tiger",
                    "penguin.label": "Pinguin",
                    "rino.label": "Nashorn",
                    "rooster.label": "Hahn",
                    "seal.label": "Robbe",
                    "snake.label": "Schlange",
                    "star.label": "Seestern",
                    "whale.label": "Wal",
                    "wolf.label": "Wolf",
                    "api.back": "&laquo; zur&uuml;ck",
                    "api.more": "&raquo; mehr Spiele",
                    "api.fullscreen": "Vollbildmodus",
                    "api.continue": "Weiter",
                    "api.play_now": "Jetzt spielen",
                    "api.ad_modal_header": "Werbung schlie\u00dft automatisch in&hellip;",
                    "api.ad_modal_header2": "Kurze Werbepause&hellip;",
                    "api.ad_modal_header3": "L\u00e4dt&hellip;",
                    "api.teaser_modal_header": "Spiele jetzt den n\u00e4chsten Teil&hellip;",
                    "api.no_abo": "Kein Abo!",
                    "api.secure_payment": "Sicheres Bezahlen!",
                    "api.paymentmethod_cc": "Kreditkarte",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.payment_cta": "Weiter"
                },
                "en": {
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                },
                "es": {
                    "bear.label": "Oso",
                    "cow.label": "Vaca",
                    "crog.label": "Cocodrilo",
                    "dolphin.label": "Delf\u00edn",
                    "fish.label": "Pescado",
                    "hamster.label": "H\u00e1mster",
                    "lion.label": "Le\u00f3n",
                    "lioness.label": "Tigre",
                    "penguin.label": "Ping\u00fcino",
                    "rino.label": "Rinoceronte",
                    "rooster.label": "Gallo",
                    "seal.label": "Foca",
                    "snake.label": "Serpiente",
                    "star.label": "Estrella de mar",
                    "whale.label": "Ballena",
                    "wolf.label": "Lobo",
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                },
                "nl": {
                    "bear.label": "Beer",
                    "cow.label": "Koe",
                    "crog.label": "Krokodil",
                    "dolphin.label": "Dolfijn",
                    "fish.label": "Vis",
                    "hamster.label": "Hamster",
                    "lion.label": "Leeuw",
                    "lioness.label": "Tijger",
                    "penguin.label": "Pingu\u00efn",
                    "rino.label": "Neushoorn",
                    "rooster.label": "Haan",
                    "seal.label": "Zeehond",
                    "snake.label": "Slang",
                    "star.label": "Zeester",
                    "whale.label": "Walvis",
                    "wolf.label": "Wolf",
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                },
                "ru": {
                    "bear.label": "\u041c\u0435\u0434\u0432\u0435\u0434\u044c",
                    "cow.label": "\u041a\u043e\u0440\u043e\u0432\u0430",
                    "crog.label": "\u041a\u0440\u043e\u043a\u043e\u0434\u0438\u043b",
                    "dolphin.label": "\u0414\u0435\u043b\u044c\u0444\u0438\u043d",
                    "fish.label": "\u0420\u044b\u0431\u0430",
                    "hamster.label": "\u0425\u043e\u043c\u044f\u043a",
                    "lion.label": "\u041b\u0435\u0432",
                    "lioness.label": "\u0422\u0438\u0433\u0440",
                    "penguin.label": "\u041f\u0438\u043d\u0433\u0432\u0438\u043d",
                    "rino.label": "\u041d\u043e\u0441\u043e\u0440\u043e\u0433",
                    "rooster.label": "\u041f\u0435\u0442\u0443\u0445",
                    "seal.label": "\u043c\u043e\u0440\u0441\u043a\u043e\u0439 \u043f\u0435\u0441",
                    "snake.label": "\u0417\u043c\u0435\u044f",
                    "star.label": "\u043c\u043e\u0440\u0441\u043a\u0430\u044f \u0437\u0432\u0435\u0437\u0434\u0430",
                    "whale.label": "\u041a\u0438\u0442",
                    "wolf.label": "\u0412\u043e\u043b\u043a",
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                },
                "pt": {
                    "bear.label": "Urso",
                    "cow.label": "Vaca",
                    "crog.label": "Crocodilo",
                    "dolphin.label": "Golfinho",
                    "fish.label": "Peixe",
                    "hamster.label": "Criceto",
                    "lion.label": "Le\u00e3o",
                    "lioness.label": "Tigre",
                    "penguin.label": "Pinguim",
                    "rino.label": "Rinoceronte",
                    "rooster.label": "Galo",
                    "seal.label": "Foca",
                    "snake.label": "Serpente",
                    "star.label": "Estrela do Mar",
                    "whale.label": "Baleia",
                    "wolf.label": "Lobo",
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                },
                "pl": {
                    "bear.label": "Nied\u017awied\u017a",
                    "cow.label": "Krowa",
                    "crog.label": "Krokodyl",
                    "dolphin.label": "Delfin",
                    "fish.label": "Ryba",
                    "hamster.label": "Chomik",
                    "lion.label": "Lew",
                    "lioness.label": "Tygrys",
                    "penguin.label": "Pingwin",
                    "rino.label": "Nosoro\u017cec",
                    "rooster.label": "Kogut",
                    "seal.label": "Foka",
                    "snake.label": "W\u0105\u017c",
                    "star.label": "Rozgwiazda",
                    "whale.label": "Wieloryb",
                    "wolf.label": "Wilk",
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                },
                "tr": {
                    "bear.label": "Ay\u0131",
                    "cow.label": "Inek",
                    "crog.label": "Timsah",
                    "dolphin.label": "Yunus",
                    "fish.label": "Bal\u0131k",
                    "hamster.label": "Hamster",
                    "lion.label": "Aslan",
                    "lioness.label": "Kaplan",
                    "penguin.label": "Penguen",
                    "rino.label": "Gergedan",
                    "rooster.label": "Horoz",
                    "seal.label": "Fok bal\u0131\u011f\u0131",
                    "snake.label": "Y\u0131lan",
                    "star.label": "Deniz Y\u0131ld\u0131z\u0131",
                    "whale.label": "Balina",
                    "wolf.label": "Kurt",
                    "api.back": "&laquo; Geri",
                    "api.more": "&raquo; Daha Fazla Oyun",
                    "api.fullscreen": "Tam ekran",
                    "api.continue": "Devam",
                    "api.play_now": "Oyna",
                    "api.ad_modal_header": "Reklam &ndash; otomatik kapanacakt\u0131r&hellip;",
                    "api.ad_modal_header2": "Reklam&hellip;",
                    "api.ad_modal_header3": "",
                    "api.teaser_modal_header": "Sonraki B\u00f6l\u00fcm&hellip;",
                    "api.no_abo": "Abonelik Yoktur!",
                    "api.secure_payment": "G\u00fcvenli \u00d6deme!",
                    "api.paymentmethod_cc": "Kredi Kart\u0131",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.payment_cta": "Sonraki"
                },
                "fr": {
                    "bear.label": "Ours",
                    "cow.label": "Vache",
                    "crog.label": "Crocodile",
                    "dolphin.label": "Dauphin",
                    "fish.label": "Poisson",
                    "hamster.label": "Hamster",
                    "lion.label": "Lion",
                    "lioness.label": "Tigre",
                    "penguin.label": "Manchot",
                    "rino.label": "Rhinoc\u00e9ros",
                    "rooster.label": "Coq",
                    "seal.label": "Phoque",
                    "snake.label": "Serpent",
                    "star.label": "\u00c9toile de mer",
                    "whale.label": "Baleine",
                    "wolf.label": "Loup",
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                }
            },
            "gameParams": {
                "languages_available": ["de", "tr", "en"],
                "flags": {
                    "exclusive": 1
                },
                "aspectRatio": 1,
                "screenshot": {
                    "active": true,
                    "areas": {
                        "default": {
                            "x": 0,
                            "y": 0,
                            "width": 100,
                            "height": 100
                        }
                    },
                    "camera": {
                        "position": ["left", "bottom"],
                        "x": 5,
                        "y": 5
                    }
                },
                "fullscreen_enabled": 1,
                "header_image": "KidsColorBook2Header.jpg"
            },
            "urlRoot": "http:\/\/play.famobi.com",
            "assetsPath": "",
            "ts": 1473615524000,
            "short_url": "http:\/\/play.famobi.com\/kids-color-book-2",
            "uuid": "03b1e156-de50-49d6-964b-01ea276eee3d",
            "pid": "4638e320-4444-4514-81c4-d80a8c662371",
            "aid": "A1000-1",
            "name": "\"Kids Color Book 2\"",
            "languages": ["de", "en", "es", "nl", "ru", "pt", "pl", "tr", "fr"],
            "ads": {
                "adsense_channels": ["7657524996", ""],
                "adx_channels": [""],
                "min_s_between": 45,
                "min_s_before": 15,
                "show_initial": false,
                "show_video": true,
                "show_click2play": false,
                "description_url": "http:\/\/play.famobi.com\/sda\/description\/kids-color-book-2?hl=en",
                "provider": "dfp",
                "dfp_available": false
            },
            "i18n": {
                "default": {
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                },
                "en": {
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                },
                "de": {
                    "api.back": "&laquo; zur&uuml;ck",
                    "api.more": "&raquo; mehr Spiele",
                    "api.fullscreen": "Vollbildmodus",
                    "api.continue": "Weiter",
                    "api.play_now": "Jetzt spielen",
                    "api.ad_modal_header": "Werbung schlie\u00dft automatisch in&hellip;",
                    "api.ad_modal_header2": "Kurze Werbepause&hellip;",
                    "api.ad_modal_header3": "L\u00e4dt&hellip;",
                    "api.teaser_modal_header": "Spiele jetzt den n\u00e4chsten Teil&hellip;",
                    "api.no_abo": "Kein Abo!",
                    "api.secure_payment": "Sicheres Bezahlen!",
                    "api.paymentmethod_cc": "Kreditkarte",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.payment_cta": "Weiter"
                },
                "es": {
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                },
                "nl": {
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                },
                "ru": {
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                },
                "pt": {
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                },
                "pl": {
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                },
                "tr": {
                    "api.back": "&laquo; Geri",
                    "api.more": "&raquo; Daha Fazla Oyun",
                    "api.fullscreen": "Tam ekran",
                    "api.continue": "Devam",
                    "api.play_now": "Oyna",
                    "api.ad_modal_header": "Reklam &ndash; otomatik kapanacakt\u0131r&hellip;",
                    "api.ad_modal_header2": "Reklam&hellip;",
                    "api.ad_modal_header3": "",
                    "api.teaser_modal_header": "Sonraki B\u00f6l\u00fcm&hellip;",
                    "api.no_abo": "Abonelik Yoktur!",
                    "api.secure_payment": "G\u00fcvenli \u00d6deme!",
                    "api.paymentmethod_cc": "Kredi Kart\u0131",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.payment_cta": "Sonraki"
                },
                "fr": {
                    "api.back": "&laquo; Back",
                    "api.more": "&raquo; More Games",
                    "api.fullscreen": "Fullscreen mode",
                    "api.ad_modal_header": "Advertisement closes in&hellip;",
                    "api.ad_modal_header2": "Advertisement&hellip;",
                    "api.ad_modal_header3": "Loading&hellip;",
                    "api.teaser_modal_header": "Continue with the next episode&hellip;",
                    "api.no_abo": "No Subscription!",
                    "api.secure_payment": "Secure Payment!",
                    "api.paymentmethod_cc": "Credit Card",
                    "api.paymentmethod_paypal": "PayPal",
                    "api.paymentmethod_sms": "SMS",
                    "api.continue": "Continue",
                    "api.play_now": "Play now",
                    "api.payment_cta": "Next"
                }
            },
            "branding": {
                "more_games_image_prefix": "https:\/\/games.cdn.famobi.com\/",
                "more_games_image": "\/portal\/4638e320-4444-4514-81c4-d80a8c662371\/564f2b86a3bf7\/more-games-button\/600x253.png",
                "more_games_url": "http:\/\/www.games1.com",
                "preload_image": "\/html5games\/gameapi\/v1\/invisPreloadImage.png",
                "test_preload_image": "\/html5games\/gameapi\/v1\/testPreloadImage.png"
            },
            "style": "\t<style type=\"text\/css\">\n\t\t\n\t<\/style>",
            "headerHtml": "",
            "menuHtml": "",
            "payHtml": ""
        },_fgq,'');
    }
    ;
    firstJS.parentNode.insertBefore(fgJS, firstJS);
};
